### ISSUE TITLE
Breeding cage number disappears if a parent is removed

### ISSUE THREAD

**Issue by charureddy** [cortex-lab/alyx#653] opened 2020-08-27 12:07 UTC
When a male/female is removed from a breeding pair on the 'breeding pairs' page, the cage number disappears. The cage number needs to be retained on the page if there is still an existing animal in that cage.

**Comment by rossant** [comment] 2020-08-31 11:16
I'm unable to reproduce this problem. Could you perhaps make step-by-step screenshots on a specific page showing this problem?

**Comment by BexTerry** [comment] 2020-09-29 11:19
here are screenshots of the issue on an example cage, but all of our breeding cages where there is only 1 parent present have this issue. The cage number has been updated, but nothing appears on the main breeding page
![image](https://user-images.githubusercontent.com/55093069/94551809-dab58a80-024d-11eb-804d-c82f1e8a5717.png)
![image](https://user-images.githubusercontent.com/55093069/94551843-e6a14c80-024d-11eb-8c6e-d358f620c3cb.png)

**Comment by rossant** [comment] 2020-09-30 07:28
Okay thanks, the problem has been identified and fixed on alyx-dev, it will be live on the main UCL alyx at the next update.

**Closed by rossant** 2020-09-30 07:28 UTC
Labels: bug
