### ISSUE TITLE
Cannot end water restriction

### ISSUE THREAD

**Issue by pipcoen** [cortex-lab/alyx#593] opened 2019-09-26 12:26 UTC
It seems that only the person who initiated a water restriction can end it? This must be a bug, as I can't see any logic behind it. I thought the issue has already been raised, but perhaps not.

**Comment by petersaj** [comment] 2019-11-15 18:21
this has been an ongoing issue that I think has been raised 3 times, can we please fix this as soon as possible?

**Comment by rossant** [comment] 2019-11-15 20:48
Is there an error message? What happens exactly in the webpage that makes it impossible to end a water restriction?

**Comment by petersaj** [comment] 2019-11-15 21:00
The fields in the water restriction object just aren't editable

**Comment by rossant** [comment] 2019-11-15 21:15
OK thanks. I found the source of the problem. There is a [commit](https://github.com/cortex-lab/alyx/commit/7d86398b22820f7f88b47bae280e49a3fdd44eb4) introduced in May, probably following someone's request (perhaps Charu?), that makes it such that users can only change their own objects. I'm not sure why this request was made in the first place. Is this still the wanted behavior? Do we want this protection just for some objects and not others? Which ones? This is a very easy fix, but we need to know the exact intended behavior...

**Comment by oliche** [comment] 2019-12-09 11:32
#615

**Comment by petersaj** [comment] 2019-12-10 12:01
Water restrictions created by one user are still not endable by another user - please let us know if there's any other information you need to fix this

**Comment by petersaj** [comment] 2020-09-10 11:44
This was never fixed - why was this issue closed multiple times? Can this change please happen, or let us know what the issue is if not?

**Comment by rossant** [comment] 2020-09-11 09:20
Hi Andy
This seems to have been not properly documented. On your [profile page](https://alyx.cortexlab.net/admin/misc/labmember/562ecd52-12da-4a66-a64a-b3c24a5858e9/change/), you should see a list of "allowed users" which is currently empty. The current policy system requires you to add the persons who can modify objects associated with you or your mice.
Could you give me the link to the water restriction you want to modify, and the list of persons who should be able to edit this object? Then we'll see if the current permission implementation is adequate or not.

**Comment by petersaj** [comment] 2020-09-11 11:50
Ah thanks, this was a whole section of Alyx which I've never heard about!
It sounds like the permissions need to go the other way - in this case the
mouse was mine, but Bex started water restriction, and I didn't have
permission to edit it. Does this mean she needs to add us to permissions,
even though she's a superuser so we shouldn't have access to everything she
does? The water restriction's ended now but here's the link to the object:
https://alyx.cortexlab.net/admin/actions/waterrestriction/bf41d1aa-20c6-498a-902b-1865a4725663/change/

**Comment by rossant** [comment] 2020-09-11 12:07
Thanks for the details. It looks like, in your case, there was a case missing in the code: a user X should be allowed to edit objects created by others *as long as these objects depend on X's own subjects*. I pushed a hot-fix on **alyx-dev**, could you confirm that you can edit the water restriction here? https://alyx-dev.cortexlab.net/admin/actions/waterrestriction/bf41d1aa-20c6-498a-902b-1865a4725663/change/
If so I'll push the fix on alyx master too

**Comment by petersaj** [comment] 2020-09-11 12:19
Yeah exactly - adding that case would be great, thanks. Yup in that link
you sent me I can edit

**Comment by rossant** [comment] 2020-09-11 12:20
Okay updated on alyx-master as well. Try again and let me know?

**Comment by petersaj** [comment] 2020-09-11 12:23
Now works, thanks!

**Comment by rossant** [comment] 2020-09-11 12:23
Excellent! Closing now, for good hopefully. Sorry for the inconvenience!

**Closed by rossant** 2020-09-11 12:23 UTC
Labels: bug, priority: high, usability
