### ISSUE TITLE
Error when adding head implant weight

### ISSUE THREAD

**Issue by sfailor** [cortex-lab/alyx#339] opened 2017-06-01 10:43 UTC
Attempted to add head implant weight to SF170215 and received this error

![image](https://cloud.githubusercontent.com/assets/15325939/26676396/839ecdd0-46bf-11e7-95f3-971803316b19.png)

**Comment by nsteinme** [comment] 2017-06-01 10:45
Yes, I can reproduce this - at the subject page I enter an implant weight
then click "save and continue editing" then get this error. Don't see why.

**Comment by rossant** [comment] 2017-06-01 10:47
There is a large number of sessions for that subject, is that normal?

**Comment by sfailor** [comment] 2017-06-01 10:49
No, appears most of them are also blank.

**Comment by rossant** [comment] 2017-06-01 10:51
That's the problem. We need to understand why many empty sessions are being created...

**Comment by nsteinme** [comment] 2017-06-01 10:51
No, I don't know why there are any sessions at all - so far we have not
implemented session creation anywhere.

**Comment by nsteinme** [comment] 2017-06-01 10:51
But, eventually there WILL be lots of sessions for many subjects.

**Comment by nsteinme** [comment] 2017-06-01 10:52
Looks like they were all created at one moment a week ago... - at the time
some migrations were done maybe?

**Comment by rossant** [comment] 2017-06-01 10:54
We can easily lift this limit but I want to understand why these sessions are being created

**Comment by nsteinme** [comment] 2017-06-01 10:54
It looks like nyx had the same thing happen, a week before that. https://alyx.cortexlab.net/sessions

**Comment by rossant** [comment] 2017-06-01 11:12
Is it okay if I delete all blank sessions?

Here's the command I'll use on the server:

```
./manage.py shell
from actions.models import Session
Session.objects.filter(users__isnull=True, procedures__isnull=True, location__isnull=True, narrative='').delete()
```

**Comment by nsteinme** [comment] 2017-06-01 11:15
I think that should be fine, yes. I will check through my matlab code to
see if there's any bit that might have accidentally added blank sessions,
but I doubt it just because there are dozens all with the exact same
timestamp...?

**Comment by rossant** [comment] 2017-06-01 11:15
I just tried and that fixes the bug on alyx-dev. I'll do it on alyx as soon as I have your green light.

The limit of 1000 will also be increased to 10000 the next time alyx is updated.

**Comment by rossant** [comment] 2017-06-01 11:16
Maybe I should add some check to prevent the creation of a blank Session (or another Action).

**Comment by nsteinme** [comment] 2017-06-01 11:16
Why was a limit of 1000 stopping this, though? There were only about 50
sessions. I don't think there are 950 other fields in the subject!

**Comment by rossant** [comment] 2017-06-01 11:17
There are 6 fields per session, we also have to add all other fields and inlines... Every single checkbox or text area or anything counts.

**Comment by rossant** [comment] 2017-06-01 11:20
OK, done! the bug should be fixed now.

**Closed** 2017-06-01 11:20 UTC
Labels: bug, priority: high
