### ISSUE TITLE
subject summary description/list

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#297] opened 2017-05-11 08:42 UTC
@charureddy has suggested it would be helpful to see a bulleted list of key actions that have happened to a subject, with dates. We'd want to discuss a little more what should be on this list but it would be things like: 

- 02 Jan 2017. Born. 
- 18 Jan 2017. Weaned. 
- 04 Feb 2017. Genotyped. 
- 15 Feb 2017. Genotype results recorded (GFP+, WT-). 
- 16 Feb 2017. Responsible user changed from Charu to Nick. 
- 16 Feb 2017. Nickname changed from CtTa_0073 to Methuselah. 
- 16 Feb 2017. Protocol changed from 1 to 3. 
- 05 May 2017. Added to Breeding Pair CtTa_BP_008. 
- 09 Dec 2033. Died.

Some of these are re-representations of information elsewhere (like the three dates at the top). But particularly of interest are the things that aren't otherwise immediately apparent, like when were genotype results added, or when did the responsible user change, or when was the mouse added to a breeding pair (or even, whether the mouse is currently in a breeding pair or not, which is not possible to see). 

I guess that if the "notes" field was instead a series of dated notes about the subject, then this would be the place to put these things - alyx would just auto-create notes about the subject for key things. So maybe this should depend on what's decided about how to do notes - one suggestion was to make any note have a subject field and a date_time, I think @petersaj and @k1o0 are thinking more about this. Another approach would be to add the information not otherwise recorded to json (where nickname history already is), and then use the json plus the other info to render this list.

**Comment by rossant** [comment] 2019-01-17 09:34
duplicate of #131

**Closed by rossant** 2019-01-17 09:34 UTC
Labels: admin, feature, priority: low
