### ISSUE TITLE
Quality control flags on session / dataset

### ISSUE THREAD

**Issue by GaelleChapuis** [cortex-lab/alyx#562] opened 2019-07-13 05:50 UTC
Opening this issue to launch the discussion about having QC flags on session/datasets.

We should have flags for
1) HW/SW QC control (eg. HW-soundBNC flag set to 1 if some trials are missing a TTL input from the sound card) 
2) analysis (eg. A-Performance flag set to 1 if the mouse does not perform up to set performance)

Exact list to be determined.

These fields will have to be searchable in DJ, so as to exclude those data with flags from analysis.

**Comment by nbonacchi** [comment] 2019-07-13 11:21
I've opened an issue in the ibllib repo (https://github.com/int-brain-lab/ibllib/issues/83) to list all the different types of QC the IBL will want to have. 
I think that in terms of Alyx the discussion should be focused more on flags, yay or nay and (if yes) what shape they should take in terms of the DB, a new table? A boolean flag for of QC ok/no-ok or something with more detail and if so in which shape or form.
I have no strong opinions on this, ultimately a qc flag is boolean either pass or not, (akin to the includeTrials datasetType) but maybe it would be interesting to capture some metadata on the process that produced the binary value, both for datasetTypes and/or sessions and for that matter any other user procedure that has an outcome that we record.
QC criteria can change over time and the info about what criteria caused the "object" to be flagged or not  should be available to future me.

**Comment by rossant** [comment] 2019-09-20 09:28
duplicate of #585 now? Reopen if I'm mistaken

**Closed by rossant** 2019-09-20 09:28 UTC
Labels: question, schema-change
