### ISSUE TITLE
re-arrange main admin site

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#108] opened 2017-02-26 11:54 UTC
Would it be possible to re-arrange the tables as they are listed on the main site? I suggest four sub-headings (Common tables, Static tables, Other, and IT admin), with the following tables under them. The sub-headings should be in this order, but within them the tables can be alphabetical if it's easier.

"Common tables"
- Subjects
- Surgeries
- Lines
- Cages
- Litters
- Virus injections
- Water restrictions
- Other actions
- Subject Requests

"Static tables" (idea here is ones that get their entries entered manually but are "one-time" in that they don't have new entries added often)
- Procedure types
- Species
- Strains
- Alleles
- Sequences
- Sources
- [all the tables currently under Equipment]

"Other" (the idea here is ones that contain data that is added automatically rather than manually (like Experiments), or that contain manually entered data but this isn't the place you'd enter it manually (like Genotype Tests, which you enter from the subject or litter page rather than directly to this table))
- Experiments
- Water administrations
- Weighings
- Genotype Tests
- Zygosities
- [all the tables currently under Behavior, Data, Electrophysiology, and Misc]

"IT admin"
- Tokens
- Groups 
- Users

**Comment by nippoo** [comment] 2017-02-28 06:27
duplicate of #62

**Comment by rossant** [comment] 2017-03-02 21:29
done

**Closed by rossant** 2017-03-02 21:29 UTC
Labels: admin, enhancement
